# Schemas
from app.schemas.common import (
    Token,
    TokenData,
    LoginRequest,
    RegisterRequest,
    RefreshTokenRequest,
    PasswordResetRequest,
    PasswordChangeRequest,
    MessageResponse,
    ErrorResponse,
    PaginationParams,
    PaginatedResponse,
    UserResponse,
    UserProfile,
    UserCreate,
    UserUpdate,
)
from app.schemas.paper import (
    PaperCreate,
    PaperUpdate,
    PaperResponse,
    PaperDetail,
    PaperListResponse,
    PaperUploadResponse,
    PaperProcessingStatus,
)
from app.schemas.podcast import (
    TranscriptEntrySchema,
    PodcastCreate,
    PodcastUpdate,
    PodcastResponse,
    PodcastDetail,
    PodcastListResponse,
    PodcastGenerationRequest,
    PodcastGenerationStatus,
)
from app.schemas.note import (
    NoteCreate,
    NoteUpdate,
    NoteResponse,
    NoteListResponse,
    ChatMessageCreate,
    ChatMessageResponse,
    ChatRequest,
    ChatResponse,
    ChatHistoryResponse,
)

__all__ = [
    # Common
    "Token",
    "TokenData",
    "LoginRequest",
    "RegisterRequest",
    "RefreshTokenRequest",
    "PasswordResetRequest",
    "PasswordChangeRequest",
    "MessageResponse",
    "ErrorResponse",
    "PaginationParams",
    "PaginatedResponse",
    "UserResponse",
    "UserProfile",
    "UserCreate",
    "UserUpdate",
    # Paper
    "PaperCreate",
    "PaperUpdate",
    "PaperResponse",
    "PaperDetail",
    "PaperListResponse",
    "PaperUploadResponse",
    "PaperProcessingStatus",
    # Podcast
    "TranscriptEntrySchema",
    "PodcastCreate",
    "PodcastUpdate",
    "PodcastResponse",
    "PodcastDetail",
    "PodcastListResponse",
    "PodcastGenerationRequest",
    "PodcastGenerationStatus",
    # Note / Chat
    "NoteCreate",
    "NoteUpdate",
    "NoteResponse",
    "NoteListResponse",
    "ChatMessageCreate",
    "ChatMessageResponse",
    "ChatRequest",
    "ChatResponse",
    "ChatHistoryResponse",
]

